### ISSUE TITLE
程序包android.support.annotation不存在

### ISSUE THREAD

**Issue by xiaomei1995** [buhuiming/BHMAndroid#1]
F:\android_mjh\OCR\BHMLibrary\src\main\java\com\bhm\sdk\bhmlibrary\base\LazyLoadFragment.java:4: 错误: 程序包android.support.annotation不存在
import android.support.annotation.Nullable;
                                 ^
F:\android_mjh\OCR\BHMLibrary\src\main\java\com\bhm\sdk\bhmlibrary\base\LazyLoadFragment.java:5: 错误: 找不到符号
import android.support.v4.app.Fragment;
                             ^
  符号:   类 Fragment
  位置: 程序包 android.support.v4.app
F:\android_mjh\OCR\BHMLibrary\src\main\java\com\bhm\sdk\bhmlibrary\base\LazyLoadFragment.java:14: 错误: 找不到符号
public abstract class LazyLoadFragment extends Fragment{

**Comment by buhuiming** [comment]
因为support包是provide，所以你可以在你的项目声明依赖，或者使用1.2.8版本。
